### ISSUE TITLE
Crash with #count

### ISSUE THREAD

**Issue by uelis** [DeMaCS-UNICAL/I-DLV#4]
We came across an example that crashes dlv 2.1.1.

File `example.asp`:
```
f(a,1).
f(b,1).

g(1).

c(X, Y) :- g(X), #count{f(a, T): T == X} = Y.
```

Execution on Linux:
```
~$ dlv-2.1.1-linux-x86_64 example.asp
DLV 2.1.1

Segmentation fault (core dumped)
```

Perhaps the specific form of #count is unsupported?

**Comment by jessicazangari** [comment]
Thanks for telling us. When handling aggregates, we missed the case in which an aggregate element contains a single built-in atom. We are going to fix it in the next I-DLV and DLV2 releases. 

You will find:
- the latest I-DLV releases in the release section of this reposity: https://github.com/DeMaCS-UNICAL/I-DLV/releases
- the latest DLV2 releases on its official web page: https://dlv.demacs.unical.it

A way to get around from the issue would be to rewrite the program as follows:
```
f(a,1).
f(b,1).

g(1).
auxiliary(T) :- T == X, g(X).
c(X, Y) :- g(X), #count{f(a, T): auxiliary(T)} = Y.
```
Finally, note that `T == X` is not a comparison but rather an assignment, i.e., `T` takes the same value of `X`.

**Comment by uelis** [comment]
Many thanks!
